a = input('Digite algo ')
print("O tipo desse valor é", type(a))
print('só tem espaços ? ', a.isspace())
print('é um número?', a.isnumeric())
print('È alfabético? ', a.isalpha())
print('È alfanumérico?', a.isalnum())
print('Está em maiúsculas?', a.isupper())
print('Está em minúsculas?', a.islower())
print('Está capitalizada?', a.istitle())
